version: '2'

services:
  mongo_db:
    image: mongo:${mongo_version}
    volumes:
      - post_db:/data/db
    networks:
      reddit:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    env_file: ./.env
    image: ${USERNAME}/ui:${ui_version}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - reddit
  post:
    build: ./post-py
    image: ${USERNAME}/post:${post_version}
    networks:
      - reddit
  comment:
    build: ./comment
    image: ${USERNAME}/comment:${comment_version}
    networks:
      - reddit
volumes:
  post_db:

networks:
  reddit:
